services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: fitai_user
      POSTGRES_PASSWORD: fitai_password
      POSTGRES_DB: fitai_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: