[pytest]
DJANGO_SETTINGS_MODULE = fitai_backend.settings
# On demande à pytest de chercher les fichiers qui finissent par tests.py ou commencent par test_
python_files = tests.py test_*.py *_tests.py
# Options par défaut (ex: on demande les avertissements, et on affiche les erreurs localisées)
addopts = -v --nomigrations --ignore=venv/