# Generated by Django 5.0.14 on 2026-06-24 10:00

import tryon.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_image', models.ImageField(upload_to=tryon.models.get_file_path_with_uuid)),
                ('garment_image', models.ImageField(upload_to=tryon.models.get_file_path_with_uuid)),
                ('garment_description', models.TextField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to=tryon.models.get_file_path_with_uuid)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
