# Generated by Django 5.0.14 on 2026-06-24 16:20

import tryon.models
import tryon.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryonrequest',
            name='garment_image',
            field=models.ImageField(upload_to=tryon.models.get_file_path_with_uuid, validators=[tryon.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='person_image',
            field=models.ImageField(upload_to=tryon.models.get_file_path_with_uuid, validators=[tryon.validators.validate_image_file]),
        ),
    ]
